### ISSUE TITLE
Lo sfondo occupa dello spazio vuoto nella home

### ISSUE THREAD

**Issue by showbiz0** [NotThatNinja/Mura-Fusion-Restaurant#3]
Nella versione da cellulare lo sfondo occupa più spazio del necessario e va in overflow

**Comment by NotThatNinja** [comment]
Link utili: [https://stackoverflow.com/questions/12686065/set-line-height-as-a-percentage-relative-to-the-parent-element](url)

**Comment by showbiz0** [comment]
Risolto utilizzando uno sfondo body
